---

- name: Basic playbook to display name and ping managed hosts
  hosts: all
  gather_facts: no
  tasks:

    - name: Debug ansible_hostname variable
      debug:
        msg: "Managed node: {{ ansible_host }}"
  
    - name: Ping Managed Nodes
      ping: 
