---

- name: Basic playbook to display name and ping managed hosts
  hosts: all
  gather_facts: no
  become: no
  
  tasks:

    - name: Debug ansible_hostname
      debug:
        var: ansible_hostname
  
    - name: Ping Management Nodes
      ping: 
