---

- name: Basic playbook to display name and ping managed hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Debug ansible_hostname variable
      debug:
        msg: "Management node: {{ ansible_host }}"
    - name: Ping Management Nodes
      ping: 
