---

- name: Cisco IOS gather facts
  hosts: ios-sw1
  gather_facts: no
  tasks:

    - name: Capture and parse 'show interfaces'
      ansible.utils.cli_parse:
        command: "show interface"
        parser:
          name: ansible.netcommon.ntc_templates
          #name: ansible.netcommon.textfsm
          #name: ansible.netcommon.pyats
          #name: ansible.netcommon.native
      register: _int_result

    - name: Debug 'show interfaces'
      debug:
        var: _int_result.parsed

    - name: Capture and parse 'show vlan'
      ansible.utils.cli_parse:
        command: "show vlan"
        parser:
          #name: ansible.netcommon.ntc_templates
          name: ansible.netcommon.pyats
      register: _int_result

    - name: Debug 'show vlan'
      debug:
        var: _int_result.parsed

    - name: Capture and parse 'show interfaces'
      ansible.utils.cli_parse:
        command: "show interface"
        parser:
          name: ansible.netcommon.ttp
          #template_path: templates/ios_show_interface.ttp
      register: _int_result

    - name: Debug 'show interfaces'
      debug:
        var: _int_result.parsed