---
# https://docs.ansible.com/ansible/latest/network/user_guide/cli_parsing.html
- name: Cisco IOS gather facts
  hosts: ios-sw1
  gather_facts: no
  tasks:

    # https://github.com/networktocode/ntc-templates
    - name: Capture and parse 'show interface' ntc_templates
      ansible.utils.cli_parse:
        command: "show interface"
        parser:
          name: ansible.netcommon.ntc_templates
          #name: ansible.netcommon.textfsm
          #name: ansible.netcommon.pyats
          #name: ansible.netcommon.native
          template_path: templates/ios_show_interface.textfsma
      register: _int_result1
    - name: Debug 'show interfaces'
      debug:
        var: _int_result1.parsed

    - name: Capture and parse 'show interface' ntc_templates
      ansible.utils.cli_parse:
        command: "show interface"
        parser:
          #name: ansible.netcommon.ntc_templatesa
          name: ansible.netcommon.textfsm
          #name: ansible.netcommon.pyats
          #name: ansible.netcommon.native
          template_path: templates/ios_show_interface.textfsm
      register: _int_result1a
    - name: Debug 'show interfaces'
      debug:
        var: _int_result1a.parsed

    - name: Capture and parse 'show interface' native
      ansible.utils.cli_parse:
        command: "show interface"
        parser:
          name: ansible.netcommon.native
          template_path: templates/ios_show_interface.yaml
        set_fact: _int_result3
      register: _int_result2
    - name: Debug 'show interfaces'
      debug:
        var: _int_result2.parsed
    - name: Debug 'show interface'
      debug:
        var: _int_result3

    - name: Capture and parse 'show vlan' pyats
      ansible.utils.cli_parse:
        command: "show vlan"
        parser:
          #name: ansible.netcommon.ntc_templates
          name: ansible.netcommon.pyats
      register: _int_result4
    - name: Debug 'show vlan'
      debug:
        var: _int_result4.parsed

    # https://github.com/google/textfsm/tree/master
    - name: Capture and parse 'show interface' textfsm
      ansible.utils.cli_parse:
        command: "show interface"
        parser:
          name: ansible.netcommon.textfsm
          #template_path: templates/ios_show_interface.textfsm
      register: _int_result5
    - name: Debug 'show interfaces'
      debug:
        var: _int_result5.parsed

    - name: Capture and parse 'show interface' ttp
      ansible.utils.cli_parse:
        command: "show interface"
        parser:
          name: ansible.netcommon.ttp
          #template_path: templates/ios_show_interface.ttp
      register: _int_result6
    - name: Debug 'show interface'
      debug:
        var: _int_result6.parsed

