---
# https://docs.ansible.com/ansible/latest/network/user_guide/cli_parsing.html
- name: Cisco IOS gather facts
  hosts: ios-sw1
  gather_facts: no
  tasks:

    - name: Run '{{ command }}' and parse with '{{ parser }}'
      ansible.utils.cli_parse:
        command: "{{ command }}"
        parser:
          name: "{{ parser }}"
      when: template == "none"
      register: _int_result

    - name: Run '{{ command }}' and parse with '{{ parser }}'
      ansible.utils.cli_parse:
        command: "{{ command }}"
        parser:
          name: "{{ parser }}"
          template_path: "templates/{{ template }}"
      when: template != "none"
      register: _int_result

    - name: Debug '{{ command }}' parsed with '{{ parser }}'
      debug:
        var: _int_result.parsed
