---
#config system global
#  set rest-api enable
#end
- name: Create Execution Environments
  hosts: cisco
  gather_facts: no
  become: no
  
  tasks:
    - name: Debug ansible_hostname
      debug:
        var: ansible_hostname
