---

- name: Cisco IOS config vlans
  hosts: cisco_sw
  gather_facts: no
  tasks:

  - name: Cisco IOS Include VLAN variables
    include_vars: main.yml

  # - name: Create vlan (DEPRECATED)
  #   cisco.ios.ios_vlan:
  #     vlan_id: 100
  #     name: vlan100
  #     state: present
  #     interfaces:
  #       - Ethernet0/1
  #       - Ethernet0/2

  - name: Cisco IOS Config vlans
    cisco.ios.ios_vlans:
      config: "{{ cisco_vlans }}"
      state: merged 
    register: _vlan
    become: yes

  - name: Debug VLAN before
    debug:
      var: _vlan.before

  - name: Debug VLAN before
    debug:
      var: _vlan.commands

  - name: Debug VLAN before
    debug:
      var: _vlan.after

  - name: Cisco IOS Add VLAN to l2 interfaces
    cisco.ios.ios_l2_interfaces:
      config: "{{ cisco_interfaces }}"
      state: merged
    become: true




