---

- name: Cisco IOS config IPs
  hosts: cisco_rtr
  gather_facts: no
  tasks:

  - name: Cisco IOS Include IP variables
    include_vars: main.yml

  - name: Cisco IOS Sets IP addresses
    cisco.ios.ios_l3_interfaces:
      config: "{{ cisco_l3_interfaces }}"
      state: merged
    register: _l3_interface
    #become: true

  - name: Cisco IOS Debug IP before
    debug:
      var: _l3_interface.before

  - name: Cisco IOS Debug IP command
    debug:
      var: _l3_interface.commands

  - name: Cisco IOS Debug IP after
    debug:
      var: _l3_interface.after
