---

- name: Cisco IOS gather facts
  hosts: cisco
  gather_facts: no
  tasks:
  - name: Cisco IOS get facts 
    cisco.ios.ios_facts:
      gather_subset:
        - all
      gather_network_resources:
        - "interfaces"
        - "l3_interfaces"
        - "vlans"
        - "bgp_global"
    register: _facts
    become: true
  - name: Set My facts
    set_fact:
      _myfacts: "{{ groups[all] }}"
  - name: Debug IOS facts
    debug:
      var: _facts
  - name: Debug My facts
    debug:
      var: _myfacts
  - name: Debug Facts
    debug:
      var: _facts,_myfacts
