---

- name: Cisco IOS config vlans
  hosts: cisco
  gather_facts: no
  tasks:
  - name: Cisco IOS Include VLAN variables
    include_vars: main.yml
  - name: Cisco IOS Config vlans
    cisco.ios.ios_vlans:
      config: "{{ cisco_vlans }}"
      state: merged 
    become: yes
  - name: Cisco IOS Add VLAN to l2 interfaces
    cisco.ios.ios_l2_interfaces:
      config: "{{ cisco_interfaces }}"
      state: merged
    become: true




