---
- name: Cisco IOS config BGP
  hosts: cisco_rtr
  gather_facts: false
  tasks:

    - name: Cisco IOS Include BGP variables
      include_vars: main.yml

    - name: Cisco IOS Sets BGP config
      cisco.ios.ios_bgp_global:
        config: "{{ cisco_bgp }}"
        state: merged
      register: _bgp
      become: true

    - name: Cisco IOS Debug BGP before
      debug:
        var: _bgp.before

    - name: Cisco IOS Debug BGP command
      debug:
        var: _bgp.commands

    - name: Cisco IOS Debug BGP after
      debug:
        var: _bgp.after

    - name: Save running to startup when modified
      cisco.ios.ios_config:
        save_when: modified
